### ISSUE TITLE
Error al cargar algunas imagenes de peliculas

### ISSUE THREAD

**Issue by EdixonAlberto** [AlexandroMunera/React-InfoPeli#1]
![image](https://user-images.githubusercontent.com/40126214/79780819-82777580-830a-11ea-9826-29856b6bba39.png)
Algunas imagenes de peliculas no cargan al principio de la busqueda, al parecer es un problema de los datos que llegan al cliente, algunos llegan vacios, tal como se muestra en la imagen.

Es buena practica tener una imagen por defecto para mostrar en el caso que suceda un error al cargar la imagen.

**Comment by AlexandroMunera** [comment]
Gracias, ahora se muestra esta imagen.

![image](https://user-images.githubusercontent.com/6957621/79891338-26dbe380-8401-11ea-867d-0dfe59073a56.png)
